### ISSUE TITLE
external_node replacement?

### ISSUE THREAD

**Issue by jorhett** [jbussdieker/ruby-enc#3]
What script from the repository should be installed on the Puppet servers to submit node reports?

Also, wanted to find out if this is stable and working, or abandoned...

**Comment by jbussdieker** [comment]
Node reports get sent from the client to the master and the master can be configured to submit those reports directly to ruby-enc via reporturl in the puppet master config (be sure the client is configured to submit them too).

That being said external_node script is separate from reports. It does the node classification (ie what class and parameters should be set). In that case the same script from puppet dashboard would suffice.

In both cases the configuration of the puppet masters should be exactly the same as if you were running puppet dashboard.
